services:
  stt:
    volumes:
      - ./.cache/stt/hf_home:/app/hf_home
    networks:
      - app-network  
  ipex-llm-ollama:
    volumes:
      - ./.cache/ollama:/root/.ollama/models
    networks:
     - app-network
